---
language: generic
# Use the new container infrastructure
sudo: required

services:
  - docker

env:
  - ANSIBLE_VERSION: 1.9
  - ANSIBLE_VERSION: 2.0
  - ANSIBLE_VERSION: 2.1
  - ANSIBLE_VERSION: 2.2

install:
  # Pull container
  - sudo docker pull kitpages/docker-ansible:$ANSIBLE_VERSION

  # Check ansible version
  - sudo docker run -it --rm -v ${PWD}:/ansible -w /ansible kitpages/docker-ansible:$ANSIBLE_VERSION ansible-playbook --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - sudo docker run -it --rm -v ${PWD}:/ansible-traefik -w /ansible-traefik kitpages/docker-ansible:$ANSIBLE_VERSION ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
